<template>
  <div>
    <h2>HTML Image 元素（ &lt;img&gt; ）代表文档中的一个图像。</h2>
    <p>使用说明：
      浏览器并不总是显示该元素中的图像。对于非图形浏览器（包括那些有视力障碍的人所使用的）来说就是这种情况，如果用户选择不显示图像，或者如果浏览器无法显示图像，因为它是无效的或 不支持的类型。在这些情况下，浏览器会用该元素的 alt 属性定义的文本来替换图像。</p>
    <h2>属性</h2>
    <span>alt</span>
    <p>这个属性定义了描述图像的替换文本。用户将看到这个显示，如果图像的URL是错误的，该图像不在 支持的格式 列表中，或者如果图像还没有被下载。</p>
    <p>
      使用说明： 省略这个属性表明该图像是内容的关键部分，但没有等效的文本可用。把这个属性设置为空字符串，表明该图像不是内容的关键部分，非可视化浏览器在渲染的时候可能会忽略它。</p>
    <pre>
    img对象
      accessKey:"h"//快捷键，alt+h
      align:""//对齐方式
      alt:""//替代文字
      assignedSlot:(...)
      attributeStyleMap
      attributes
      autocapitalize
      baseURI
      border
      childElementCount
      childNodes
      children
      classList
      className
      clientHeight
      clientLeft
      clientTop
      clientWidth
      complete
      contentEditable
      crossOrigin
      currentSrc
      dataset
      decoding
      dir
      draggable
      firstChild
      firstElementChild
      height
      hidden
      hspace
      id
      innerHTML
      innerText
      inputMode
      isConnected
      isContentEditable
      isMap
      lang
      lastChild
      lastElementChild
      localName
      longDesc
      lowsrc
      name
      namespaceURI
      naturalHeight
      naturalWidth
      nextElementSibling
      nextSibling
      nodeName
      nodeType
      nodeValue
      nonce
      offsetHeight
      offsetLeft
      offsetParent
      offsetTop
      offsetWidth
      onabort
      onauxclick
      onbeforecopy
      onbeforecut
      onbeforepaste
      onblur
      oncancel
      oncanplay
      oncanplaythrough
      onchange
      onclick
      onclose
      oncontextmenu
      oncopy
      oncuechange
      oncut
      ondblclick
      ondrag
      ondragend
      ondragenter
      ondragleave
      ondragover
      ondragstart
      ondrop
      ondurationchange
      onemptied
      onended
      onerror
      onfocus
      ongotpointercapture
      oninput
      oninvalid
      onkeydown
      onkeypress
      onkeyup
      onload
      onloadeddata
      onloadedmetadata
      onloadstart
      onlostpointercapture
      onmousedown
      onmouseenter
      onmouseleave
      onmousemove
      onmouseout
      onmouseover
      onmouseup
      onmousewheel
      onpaste
      onpause
      onplay
      onplaying
      onpointercancel
      onpointerdown
      onpointerenter
      onpointerleave
      onpointermove
      onpointerout
      onpointerover
      onpointerup
      onprogress
      onratechange
      onreset
      onresize
      onscroll
      onsearch
      onseeked
      onseeking
      onselect
      onselectstart
      onstalled
      onsubmit
      onsuspend
      ontimeupdate
      ontoggle
      onvolumechange
      onwaiting
      onwebkitfullscreenchange
      onwebkitfullscreenerror
      onwheel
      outerHTML
      outerText
      ownerDocument
      parentElement
      parentNode
      prefix
      previousElementSibling
      previousSibling
      referrerPolicy
      scrollHeight
      scrollLeft
      scrollTop
      scrollWidth
      shadowRoot
      sizes
      slot
      spellcheck
      src
      srcset
      style
      tabIndex
      tagName
      textContent
      title
      translate
      useMap
      vspace
      width
      x
      y
      __proto__
      :
      HTMLImageElement
    </pre>
  </div>
</template>
